[tool.poetry]
name = "rich-tools"
version = "0.1.1"
description = "A python package with helpful tools when working with the rich python library."
authors = ["Avi Perl <avi@aviperl.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/avi-perl/rich_tools"
keywords = ["rich", "pandas"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.12.0"
pandas = "^1.3.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.9b0"
coverage = "^6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
