[tool.poetry]
name = "rich-tools"
version = "0.4.0"
description = "A python package with helpful tools when working with the rich python library."
authors = ["Avi Perl <avi@aviperl.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/avi-perl/rich_tools"
keywords = ["rich", "pandas"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.12.0"
pandas = "^1.3.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.9b0"
coverage = "^6.0.1"
pytest-cov = "^3.0.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
